# TACO Dataset Configuration
path: /home/luc/ai-ml/MLOPS/PROJECT/data/taco_dataset_processed_modified
train: train/images
val: valid/images
test: test/images

nc: 18
names: ['Aluminium foil', 'Bottle', 'Bottle cap', 'Broken glass', 'Can', 'Carton', 'Cigarette', 'Cup', 'Lid', 'Other litter', 'Other plastic', 'Paper', 'Plastic bag - wrapper', 'Plastic container', 'Pop tab', 'Straw', 'Styrofoam piece', 'Unlabeled litter']